<?php
$this->headTitle('Add Event');

/** @var \Zend\Form\Form $form */
//$form = $this->form;

$form->setAttribute('action', $this->url('event', ['action' => 'add']));
$form->prepare();

$eventDate = $form->get('event-date-time');
$title = $form->get('title');
$description = $form->get('description');

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($eventDate) ?>
    <?= $this->formElement($eventDate) ?>
    <?= $this->formElementErrors()->render($eventDate, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>


<?php

echo $this->formSubmit($form->get('submit'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();